# Generated by Django 4.2 on 2024-04-06 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('page_count', models.IntegerField()),
                ('category', models.CharField(choices=[('horror', 'Horror'), ('mystery', 'Mystery'), ('science fiction', 'Science Fiction'), ('historical fiction', 'Historical Fiction'), ('romance', 'Romance'), ('fantasy', 'Fantasy'), ('autobiography', 'Autobiography'), ('adventure', 'Adventure'), ('history', 'History')], max_length=30)),
                ('author_name', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
