# Generated by Django 4.2 on 2024-04-06 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_alter_book_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={},
        ),
    ]
