# Generated by Django 4.2 on 2024-04-06 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_alter_book_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'book'},
        ),
    ]
