# Generated by Django 4.2 on 2024-04-07 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_alter_book_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'book', 'verbose_name_plural': 'books'},
        ),
    ]
