# Generated by Django 4.2 on 2024-04-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_book_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='category',
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('horror', 'Horror'), ('mystery', 'Mystery'), ('science fiction', 'Science Fiction'), ('historical fiction', 'Historical Fiction'), ('romance', 'Romance'), ('fantasy', 'Fantasy'), ('autobiography', 'Autobiography'), ('adventure', 'Adventure'), ('history', 'History')], max_length=30, verbose_name='genre')),
                ('products', models.ManyToManyField(to='market.book')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
    ]
