# Generated by Django 4.2 on 2024-04-15 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_remove_book_category_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='products',
            new_name='books',
        ),
    ]
