# Generated by Django 4.2 on 2024-04-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0014_alter_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='books',
            field=models.ManyToManyField(to='market.book', verbose_name='books'),
        ),
    ]
